import sys
print('|\\   ___  |\\//| //\\     |            //___) //\\     ^       ___   |   |')
print('| >  //___ |    | <  >  |\\|           //  \\  <  >   //_\\    //     |___|')
print('|// /_____ |    |  \/   |\\|          //    \\ \\//  //   \\  (_____  |   |')
print('           |                                 \\                       |    ')
print('                   U   N   D   E   R   G   R   O   U   N   D')
print('                                      cDc')
print('                                     _   _')
print('                                    ((___))')
print('                                    [ x x ]')
print('                          cDc        \   /        cDc')
print('                                     (   ) ')
print('                                      (U)')
print('               ..and none but the Bovine survived the onslaught')
print('                      -cDc-   CULT OF THE DEAD COW   -cDc-')
print('                               cDc communications')
print('                          -cDc-   BASE SYSTEM   -cDc-')
print('- .... .. ...  --- -. . ...  - .-. .. -.-. -.- -.-- --..--  .. - ')
print('                                HAVE A NICE DAY')
print('.- .-.. .-..  .- -... --- ..- -  --. . - - .. -. --.  - .... . ')
print('                            xXx  FUCK SHIT UP  xXx')
print('.-.. . - - . .-. ...  .. -.  --- .-. -.. . .-.')
print(' ......82 megs............300/1200/2400 baud......86400 seconds per day.....')
print( ' Jester of Monochrome')
print(  'SysButthead           : RUGRAT')
codebook = open('codebook.txt','r').read()
flag = codebook[4] + codebook[16] + codebook[13] + codebook[3] + codebook[4] + codebook[13] + codebook[10] + codebook[26] + codebook[0] + codebook[21] + codebook[21] + codebook[8] + codebook[25] + codebook[6] + codebook[14] + codebook[2] + codebook[4] + codebook[27]
print(flag)
